language: c
services: docker
install:
    - wget https://raw.githubusercontent.com/xenserver/xenserver-build-env/master/utils/travis-build-repo.sh
script: bash travis-build-repo.sh
sudo: true
env:
    global:
        - REPO_PACKAGE_NAME=rrdd-plugins
        - REPO_CONFIGURE_CMD=true
        - REPO_BUILD_CMD=make
        - REPO_TEST_CMD=true
